// Amber Mine Editorial — vanilla interactions only; no tracking and no external runtime dependencies.
const pages=[
 ['Игра Falling Pickaxe','falling-pickaxe.html','механика правила pixmove'],['Falling Pickaxe демо','falling-pickaxe-demo.html','демо бесплатно интерфейс'],['Falling Pickaxe бонусы','falling-pickaxe-bonus.html','бонус отыгрыш wagering'],['Промокод Falling Pickaxe','falling-pickaxe-promo-code.html','промокод условия'],['Falling Pickaxe фриспины','falling-pickaxe-free-spins.html','фриспины вращения'],['Falling Pickaxe без депозита','falling-pickaxe-without-deposit.html','без депозита бонус'],['Falling Pickaxe с депозитом','falling-pickaxe-with-deposit.html','депозит rollover'],['Как играть в Falling Pickaxe','how-to-play-falling-pickaxe.html','пошаговое руководство'],['FAQ Falling Pickaxe','faq.html','вопросы ответы'],['Блог Falling Pickaxe','blog.html','статьи'],['Ответственная игра','responsible-gambling.html','лимиты помощь'],['Контакты','contacts.html','обратная связь']
];
const q=s=>document.querySelector(s), qa=s=>document.querySelectorAll(s);
const menu=q('.menu-toggle'), nav=q('.primary-nav');
if(menu&&nav){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);});}
qa('[data-search-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const input=form.querySelector('input');const status=form.querySelector('[data-search-status]');const term=input.value.trim().toLowerCase();if(!term){status.textContent='Введите слово или фразу для поиска.';return}const results=pages.filter(p=>(p[0]+' '+p[2]).toLowerCase().includes(term));if(!results.length){status.textContent=`Ничего не найдено по запросу «${input.value}». Попробуйте: демо, бонусы или правила.`;return}status.innerHTML=`Найдено: ${results.length}. `+results.map(p=>`<a class="text-link" href="${p[1]}">${p[0]}</a>`).join(' · ')}));
qa('[data-demo-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const email=form.querySelector('#demo-email'),pass=form.querySelector('#demo-password'),status=form.querySelector('[data-form-status]');let ok=true;form.querySelectorAll('.field-error').forEach(x=>x.textContent='');if(!email.checkValidity()){form.querySelector('[data-error="email"]').textContent='Укажите демонстрационный e-mail.';ok=false}if(!pass.checkValidity()){form.querySelector('[data-error="password"]').textContent='Пароль должен содержать минимум 6 символов.';ok=false}const consent=form.querySelector('#demo-consent');if(consent&&!consent.checked){form.querySelector('[data-error="consent"]').textContent='Подтвердите, что это демо-форма.';ok=false}if(!ok){status.textContent='Проверьте поля формы.';return}if(form.querySelector('#save-demo')?.checked){sessionStorage.setItem('fallingPickaxeDemoEmail',email.value);status.textContent='Демонстрационные данные сохранены только в sessionStorage этого браузера.'}else status.textContent='Проверка пройдена. Данные никуда не отправлены.'}));
const back=q('[data-back-top]');if(back){window.addEventListener('scroll',()=>back.classList.toggle('visible',window.scrollY>500),{passive:true});back.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));}
